name: Process info file

permissions:
  contents: write

on:
  push:
    paths:
      - 'UserData/**'

jobs:
  AddData:
    runs-on: nrec-large
    container:
      image: nmrlipids/core
    env:
      NMLDB_DATA_PATH: ${{ github.workspace }}/BilayerData
      NMLDB_SIMU_PATH: ${{ github.workspace }}/BilayerData/Simulations
    steps:
      - name: Checkout BilayerData (this repository)
        uses: actions/checkout@v4
        with:
          path: BilayerData

      - name: Checkout Databank
        uses: actions/checkout@v4
        with:
          repository: MagnusSletten/Databank
          ref: dev_info_process
          path: Databank

      - name: Compute new data
        env:
          TQDM_DISABLE: "True"
        working-directory: "Databank" 
        run: |
          pip install -e .  -r ./Scripts/DatabankLib/requirements-dev.txt
          python Scripts/WorkflowScripts/DockerRunInstructions/ProcessUserInfoFile.py
          - name: Commit & push updated simulations
       
      - name: Commit & push updated simulations
        uses: EndBug/add-and-commit@v9   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cwd: BilayerData            
          add: "${{ env.NMLDB_SIMU_PATH }}/*"   
          message: "Automated addition of simulation data"
          default_author: github_actions        

