name: Process info file

permissions:
  contents: write

on:
  push:
    paths:
      - 'UserData/**'

jobs:
  AddData:
    runs-on: nrec-large
    container:
      image: nmrlipids/core
    env:
      NMLDB_DATA_PATH: ${{ github.workspace }}/BilayerData
      NMLDB_SIMU_PATH: ${{ github.workspace }}/BilayerData/Simulations
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path:  ${{ github.workspace }}

      - name: Check out Databank
        uses: actions/checkout@v4
        with:
          repository: MagnusSletten/Databank
          ref: dev_info_process
          path:  ${{ github.workspace }}

      - name: Computing new data
        # now “Databank” unambiguously refers to $GITHUB_WORKSPACE/Databank
        working-directory:  ${{ github.workspace }}/Databank
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TQDM_DISABLE: "True"
        run: |
          pip install -e . -r Scripts/DatabankLib/requirements-dev.txt 
          python Scripts/WorkflowScripts/DockerRunInstructions/GetNewData.py