name: Validate Data

on: 
    pull_request_target: 
        branches: main
        paths: Molecules/**
jobs: 
    Validate_Databank:
        if: github.repository == 'NMRLipids/BilayerData' 
        runs-on: ubuntu-latest
        container:
            image: nmrlipids/core
            options: --user 1001:118
        env:
            NMLDB_DATA_PATH: ${{ github.workspace }}/BilayerData
            NMLDB_SIMU_PATH: ${{ github.workspace }}/BilayerData/Simulations
        steps:
          - name: Checkout BilayerData
            uses: actions/checkout@v4
            with:
                repository: ${{ github.event.pull_request.head.repo.full_name }}
                ref: ${{ github.event.pull_request.head.ref }}
                path: BilayerData

          - name: Checkout Databank
            uses: actions/checkout@v4
            with:
                repository: NMRlipids/Databank
                ref: main
                path: Databank
            
          - name: Install
            working-directory: "Databank"
            run: |
               pip install -e . -r ./Scripts/DatabankLib/requirements.txt

          - name: Validate
            working-directory: "Databank"
            run: |
              python Scripts/WorkflowScripts/ValidateData.py



            